Applying changes for features

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -40,19 +40,19 @@ init() {
   require_git_repo
   require_gitflow_initialized
   gitflow_load_settings
-  PREFIX=$(git config --get gitflow.prefix.feature)
+  PREFIX=$(git config --get git${COMMAND_PREFIX}flow.prefix.feature)
 }
 
 usage() {
-  echo "usage: git flow feature [list] [-v]"
-  echo "       git flow feature start [-F] <name> [<base>]"
-  echo "       git flow feature finish [-rFkDS] [<name|nameprefix>]"
-  echo "       git flow feature publish <name>"
-  echo "       git flow feature track <name>"
-  echo "       git flow feature diff [<name|nameprefix>]"
-  echo "       git flow feature rebase [-i] [<name|nameprefix>]"
-  echo "       git flow feature checkout [<name|nameprefix>]"
-  echo "       git flow feature pull [-r] <remote> [<name>]"
+  echo "usage: git ${COMMAND_PREFIX}flow feature [list] [-v]"
+  echo "       git ${COMMAND_PREFIX}flow feature start [-F] <name> [<base>]"
+  echo "       git ${COMMAND_PREFIX}flow feature finish [-rFkDS] [<name|nameprefix>]"
+  echo "       git ${COMMAND_PREFIX}flow feature publish <name>"
+  echo "       git ${COMMAND_PREFIX}flow feature track <name>"
+  echo "       git ${COMMAND_PREFIX}flow feature diff [<name|nameprefix>]"
+  echo "       git ${COMMAND_PREFIX}flow feature rebase [-i] [<name|nameprefix>]"
+  echo "       git ${COMMAND_PREFIX}flow feature checkout [<name|nameprefix>]"
+  echo "       git ${COMMAND_PREFIX}flow feature pull [-r] <remote> [<name>]"
 }
 
 cmd_default() {
@@ -72,7 +72,7 @@ cmd_list() {
     warn ""
     warn "You can start a new feature branch:"
     warn ""
-    warn "    git flow feature start <name> [<base>]"
+    warn "    git ${COMMAND_PREFIX}flow feature start <name> [<base>]"
     warn ""
     exit 0
   fi
@@ -225,7 +225,7 @@ cmd_start() {
   echo ""
   echo "Now, start committing on your feature. When done, use:"
   echo ""
-  echo "     git flow feature finish $NAME"
+  echo "     git ${COMMAND_PREFIX}flow feature finish $NAME"
   echo
 }
 
@@ -301,11 +301,11 @@ cmd_finish() {
 
   # if the user wants to rebase, do that first
   if flag rebase; then
-    if ! git flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
+    if ! git ${COMMAND_PREFIX}flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
       warn "Finish was aborted due to conflicts during rebase."
       warn "Please finish the rebase manually now."
       warn "When finished, re-run:"
-      warn "    git flow feature finish '$NAME' '$DEVELOP_BRANCH'"
+      warn "    git ${COMMAND_PREFIX}flow feature finish '$NAME' '$DEVELOP_BRANCH'"
       exit 1
     fi
   fi
@@ -335,7 +335,7 @@ cmd_finish() {
     echo "    git commit"
     echo
     echo "You can then complete the finish by running it again:"
-    echo "    git flow feature finish $NAME"
+    echo "    git ${COMMAND_PREFIX}flow feature finish $NAME"
     echo
     exit 1
   fi
@@ -476,7 +476,7 @@ avoid_accidental_cross_branch_action() {
   local current_branch=$(git_current_branch)
   if [ "$BRANCH" != "$current_branch" ]; then
     warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
-    warn "To avoid unintended merges, git-flow aborted."
+    warn "To avoid unintended merges, git-${COMMAND_PREFIX}flow aborted."
     return 1
   fi
   return 0
